# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint CI

on: push
env:
  NODE_VERSION: 16.13.2
  PACKAGE_MANAGER: yarn

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: ${{ env.PACKAGE_MANAGER }}

    - name: Installing dependencies
      run: ${{ env.PACKAGE_MANAGER }}

    - name: Linting
      run: ${{ env.PACKAGE_MANAGER }} lint
